// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw-BZj6mdnnEYt8QRsSj7pyHmtqUeHpmc',
    appId: '1:910020635245:web:57c361885fa4e0c3112d64',
    messagingSenderId: '910020635245',
    projectId: 'hrmsproject-12847',
    authDomain: 'hrmsproject-12847.firebaseapp.com',
    storageBucket: 'hrmsproject-12847.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT5haxho4YdiQedjmixzHPiz2_1PlTSB4',
    appId: '1:910020635245:android:5c0be435bf1f7e0d112d64',
    messagingSenderId: '910020635245',
    projectId: 'hrmsproject-12847',
    storageBucket: 'hrmsproject-12847.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkvDVEz1a7XRSZ9jb6tbTDdSKzt-3mHpg',
    appId: '1:910020635245:ios:f80691cbbface5e6112d64',
    messagingSenderId: '910020635245',
    projectId: 'hrmsproject-12847',
    storageBucket: 'hrmsproject-12847.firebasestorage.app',
    iosBundleId: 'com.example.hrmsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkvDVEz1a7XRSZ9jb6tbTDdSKzt-3mHpg',
    appId: '1:910020635245:ios:f80691cbbface5e6112d64',
    messagingSenderId: '910020635245',
    projectId: 'hrmsproject-12847',
    storageBucket: 'hrmsproject-12847.firebasestorage.app',
    iosBundleId: 'com.example.hrmsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw-BZj6mdnnEYt8QRsSj7pyHmtqUeHpmc',
    appId: '1:910020635245:web:9d27cf3e3fc06929112d64',
    messagingSenderId: '910020635245',
    projectId: 'hrmsproject-12847',
    authDomain: 'hrmsproject-12847.firebaseapp.com',
    storageBucket: 'hrmsproject-12847.firebasestorage.app',
  );
}
